config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  resources :users, :except => [:destroy, :edit, :update]
  resources :questions do
    resources :answers, :except => [:show, :index]
      member do
        post 'upvote'
      end
  end

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :votes, dependent: :destroy
  validates :content, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :votes, :as => :voteable, dependent: :destroy
  has_many :answers, dependent: :destroy
  validates :title, :presence => true
  validates :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes, :as => :voteable
  has_many :questions
  validates :name, presence: true
  validates_uniqueness_of :name
  validates :email, presence: true
  validates_uniqueness_of :email

  def self.authenticate(name)
    user = User.where(name: name).first
    if user
      user
    else
      nil
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :require_user, only: [:new]

  def upvote
    @answer = Answer.find(params[:id])
    @answer.votes.create
    redirect_to(answers_path)
  end


  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save
      flash[:notice] = 'Answer add to ' + @question.title
      redirect_to question_path(@answer.question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      flash[:notice] = 'Answer has been changed.'
      redirect_to question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to question_path(@answer.post)
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in.'
      redirect_to log_in_path
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_action :require_user, only: [:new]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @user = @question.user
    @answers = @question.answers
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = @question.title + 'has been updated.'
      redirect_to questions_path
    else
      render :edit
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    @question.save
    respond_to do |format|
      format.html { redirect_to questions_path }
      format.js
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if (@question.user_id == current_user.id)
      @question.destroy
      redirect_to questions_path
    else
      redirect_to root_path
    end
  end

  private
  def question_params
    params.require(:question).permit(:content, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name:params[:name])
      if User.authenticate(params[:name])
        flash[:notice] = "You've been logged in"
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:error] = 'User name entered incorrectly.'
        render 'new'
      end
    end

    def destroy
      if session[:user_id] != nil
        session[:user_id] = nil
        flash[:notice] = "You've been logged out successfully."
        redirect_to root_path
      else
        flash[:notice] = "No active session."
        redirect_to root_path
      end
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def index
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions.all
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Welcome to the the site!'
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = 'Error creating profile'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create

    @context = context
    @vote = @context.votes.new
    @vote.total = 0

    if @vote.save
      redirect_to vote_url(context)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<%= form_for answer, remote: true do |f| %>
 <%= answer.content %>
<% end %>

  <br>
  <% if (current_user) %>
    <% if (answer.user_id == current_user.id) %>
      <%= link_to 'edit', edit_question_path(question), id: 'edit_question', remote: true %>
      <%= link_to 'remove', question, method: :delete, data: {confirm: 'Delete message?'}, remote: true %>
  <% end %>
<% end %>

app/views/answers/_form.html.erb
<% render 'layouts/errors', :object => @answer %>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<h4>Edit Answer</h4>

<%= render 'form' %>

app/views/answers/new.html.erb
<h4> New Answer for <%= @question.title %></h4>

<%= render 'form' %>

app/views/answers/new.js.erb
$('#new_answer').hide().after('<%= j render('form') %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h4>Error message</h4>

  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class=navbar><%= link_to 'Register ', new_user_path %> | <%= link_to 'Sign in', log_in_path %> | <%= link_to 'Sign out.', log_out_path %></div>

<%= yield %>

<%= flash[:alert] %>
<%= flash[:notice] %>

</body>
</html>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/questions/_question.html.erb
<%= form_for question, remote: true do |f| %>
  <%= link_to question.title, question_path(question), id: 'show_question', remote: true %>
  <br>
  <% if (current_user) %>
    <% if (question.user_id == current_user.id) %>
      <%= link_to 'edit', edit_question_path(question), id: 'edit_question', remote: true %>
      <%= link_to 'remove', question, method: :delete, data: {confirm: 'Delete message?'}, remote: true %>
    <% else %>
      <%= link_to 'answer question', new_question_answer_path(question), id: 'new_answer', remote: true %>
    <% end %>
  <% end %>
<% end %>

app/views/questions/_show.html.erb
<%= form_for @question, remote: true do |f| %>
  <h4> <%= @question.title %> </h4>
  <p> <%= @user.name %> </p>
  <%= link_to 'edit', edit_question_path(@question), id: 'edit_question', remote: true %>
  <%= link_to 'remove', @question, method: :delete, data: {confirm: 'Delete message?'}, remote: true %>

  <p>
    <%= @question.content %>
  </p>

  <%= link_to 'Answer Question', new_question_answer_path(@question) %>

  <br>

  <h5> Answers </h5>
    <%= render @answers %>

<% end %>

app/views/questions/edit.html.erb
<h4>Edit Question</h4>
<%= render 'form' %>

app/views/questions/edit.js.erb
$('#edit_question').hide().after('<%= j render('form') %>');

app/views/questions/index.html.erb
<h4> Stack Overflow Clone </h4>

<p>
  <%= link_to 'Enter a New Question', new_question_path %>
</p>

<%= render @questions %>

app/views/questions/new.html.erb
<h4>New Question</h4>
<%= render 'form' %>

app/views/questions/new.js.erb
$('#new_question').hide().after('<%= j render('form') %>');

app/views/questions/show.html.erb
<h4> <%= @question.title %> </h4>
<p> <%= @user.name %> </p>
  <%= link_to edit_question_path(@question) do %> Edit <% end %>
  <%= link_to question_path(@question), :data => {:method => 'delete'} do %> Delete <% end %>

  <p>
    <%= @question.content %>
  </p>

  <%= link_to new_question_answer_path(@question) do %>
    Answer Question
  <% end %>

  <br>

  <h5> Answers </h5>

  <% @question.answers.each do |answer| %>
    <li>
      <%= answer.content %>
        <%= link_to edit_question_answer_path(@question, answer) do %>Edit<% end %>
        <%= link_to  question_answer_path(@question, answer), :data => {:method => 'delete'} do %> Delete <% end %>
    </li>
  <% end %>

app/views/questions/show.js.erb
$('#show_question').hide().after('<%= j render('show') %>');

app/views/users/_form.html.erb
<%= form_for User.new do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.submit 'Sign Up' %>
<% end %>

app/views/users/new.html.erb
<h4> Sign Up </h4>
<%= render 'form' %>

app/views/users/show.html.erb
<h4> User Page </h4>

<% @questions.each do |question| %>
  <%= link_to question.title, question_path(question) %>
<% end %>

<%= link_to 'Home', root_path %>